name: Deploy to CDC Azure as Container App

on:
  registry_package:
    types: [published]
  workflow_call:
  workflow_dispatch:
    inputs:
      target_environment:
        description: 'Target environment'
        required: true
        default: development
        type: choice
        options:
          - production
          - development

# Defines two custom environment variables for the workflow. These are used for the Container registry domain, and a name for the Docker image that this workflow builds.
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}


# There is a single job in this workflow. It's configured to run on the latest available version of Ubuntu.
jobs:
  deploy-aca:
      runs-on: ubuntu-latest
      environment: ${{ inputs.target_environment || 'production'}}
      steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy container
        uses: azure/container-apps-deploy-action@v2
        with:
          imageToDeploy: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:edge
          containerAppName: ${{ vars.ACA_NAME }}
          resourceGroup: ${{ vars.ACA_RESOURCE_GROUP }}
          containerAppEnvironment: ${{ vars.ACA_APP_ENVIRONMENT }}
          disableTelemetry: true
      - name: Update revision
        uses: azure/CLI@v2
        with:
          azcliversion: latest
          inlineScript: |
            az containerapp update \
            --name ${{ vars.ACA_NAME }} \
            --resource-group ${{ vars.ACA_RESOURCE_GROUP }} \
            --image ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:edge \
            --revision-suffix gha-${{ github.run_id }}-${{ github.run_attempt }}